### ISSUE TITLE
 error: libnids-1.24/src/libnids.a: No such file or directory

### ISSUE THREAD

**Issue by sridharsai84** [MITRECND/pynids#3]
hi,

can any1 help on this error

i successfully configured " libnids-1.24.tar.gz"

but still get this error when i do python setup.py install

x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/nidsmodule.o libnids-1.24/src/libnids.a -L/usr/local/lib -lpcap -lnet -lglib-2.0 -lgthread-2.0 -o build/lib.linux-x86_64-2.7/nidsmodule.so
x86_64-linux-gnu-gcc: error: libnids-1.24/src/libnids.a: No such file or directory
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by karthikdandavathi** [comment]
i have the same issue .. when i am trying to install from https://jon.oberheide.org/pynids/ i get the above error.. Any suggestions .. how to fix this ?
